# Generated by KFP.
# ... and modified by gchaperon

FROM python:3.10-slim

WORKDIR /usr/local/src/kfp/components

# NOTE: git is required because our versioning logic revolves around git tags
RUN apt-get update
RUN apt-get -y install git

COPY . .
RUN pip install \
    --disable-pip-version-check \
    --root-user-action=ignore \
    --no-cache-dir \
    --constraint requirements.txt \
    -e .
