# PIPELINE DEFINITION
# Name: math-pipeline
# Inputs:
#    a: int
#    b: int
#    c: int
# Outputs:
#    Output: int
components:
  comp-add:
    executorLabel: exec-add
    inputDefinitions:
      parameters:
        a:
          parameterType: NUMBER_INTEGER
        b:
          parameterType: NUMBER_INTEGER
    outputDefinitions:
      parameters:
        Output:
          parameterType: NUMBER_INTEGER
  comp-add-2:
    executorLabel: exec-add-2
    inputDefinitions:
      parameters:
        a:
          parameterType: NUMBER_INTEGER
        b:
          parameterType: NUMBER_INTEGER
    outputDefinitions:
      parameters:
        Output:
          parameterType: NUMBER_INTEGER
deploymentSpec:
  executors:
    exec-add:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - add
        command:
        - python3
        - -m
        - kfp.dsl.executor_main
        image: us-central1-docker.pkg.dev/pipelines-from-scratch/components/add:0.1.0
        resources:
          resourceCpuLimit: 100m
    exec-add-2:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - add
        command:
        - python3
        - -m
        - kfp.dsl.executor_main
        image: us-central1-docker.pkg.dev/pipelines-from-scratch/components/add:0.1.0
        resources:
          resourceCpuLimit: 100m
pipelineInfo:
  name: math-pipeline
root:
  dag:
    outputs:
      parameters:
        Output:
          valueFromParameter:
            outputParameterKey: Output
            producerSubtask: add-2
    tasks:
      add:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-add
        inputs:
          parameters:
            a:
              componentInputParameter: a
            b:
              componentInputParameter: b
        taskInfo:
          name: add
      add-2:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-add-2
        dependentTasks:
        - add
        inputs:
          parameters:
            a:
              taskOutputParameter:
                outputParameterKey: Output
                producerTask: add
            b:
              componentInputParameter: c
        taskInfo:
          name: add-2
  inputDefinitions:
    parameters:
      a:
        parameterType: NUMBER_INTEGER
      b:
        parameterType: NUMBER_INTEGER
      c:
        parameterType: NUMBER_INTEGER
  outputDefinitions:
    parameters:
      Output:
        parameterType: NUMBER_INTEGER
schemaVersion: 2.1.0
sdkVersion: kfp-2.10.1
