[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pipelines-from-scratch"
version = "0.1.0"
dependencies = ["kfp"]

[project.optional-dependencies]
# NOTE: ruff version should be kept in sync with the one declared in
# .pre-commit-config.yaml. Ruff added as dev dependency for developer
# convinience
dev = ["jupyterlab", "pre-commit", "ruff==0.8.0"]
