[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pipelines-from-scratch"
version = "0.1.0"
dependencies = ["kfp"]

[project.optional-dependencies]
dev = ["jupyterlab"]