name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        run: |
          import os
          import sys
          print(os.environ['PATH'])
          print(sys.version)
        shell: python
      - run: pip install numpy
      - name: Check numpy
        run: |
          import numpy as np
          print(np.version.version)
        shell: python
